export interface ForgeModCatalogCategory {
  id: string;
  label: string;
  description: string;
  slugs: string[];
}

export const FORGE_119_GAME_VERSION = '1.19';
export const FORGE_119_LOADER = 'forge';

/** Slugs alternativos cuando el id curado no coincide con Modrinth. */
export const FORGE_119_SLUG_ALIASES: Record<string, string> = {};

export function normalizeForge119Slug(slug: string): string {
  const key = slug.trim().toLowerCase();
  return FORGE_119_SLUG_ALIASES[key] ?? key;
}

/** Modrinth search terms used by "Ver más" per category. */
export const FORGE_119_CATEGORY_SEARCH: Record<string, string> = {
  aventura: 'adventure exploration structures',
  dimensiones: 'dimension portal mod',
  terror: 'horror scary creatures',
  magia: 'magic spells arcane',
  tecnologia: 'technology automation machines',
  construccion: 'decoration building blocks furniture',
  naturaleza: 'mobs animals nature',
  comida: 'food farming cooking',
  almacenamiento: 'storage chests inventory',
  shaders: 'performance graphics rendering',
  utilidad: 'utility hud map interface',
  rendimiento: 'performance optimization lag',
  combate: 'combat weapons bosses',
  'calidad-vida': 'quality of life',
};

/** Curated Forge 1.19.2 mods grouped by play style (Modrinth slugs). */
export const FORGE_119_MOD_CATALOG: ForgeModCatalogCategory[] = [
  {
    id: 'aventura',
    label: 'Aventura',
    description: 'Exploración, estructuras y progresión en el mundo',
    slugs: [
      'waystones',
      'biomes-o-plenty',
      'supplementaries',
      'explorers-compass',
      'when-dungeons-arise',
      'structory',
      'repurposed-structures',
      'towns-and-towers',
      'natures-compass',
      'better-advancements',
      'yungs-api',
      'yungs-better-mineshafts',
      'yungs-better-strongholds',
      'dungeons-arise-seven-seas',
      'alexs-caves',
    ],
  },
  {
    id: 'dimensiones',
    label: 'Dimensiones',
    description: 'Nuevos mundos, portales y biomas extra',
    slugs: [
      'the-twilight-forest',
      'aether',
      'deep-aether',
      'eternal-starlight',
      'undergarden',
      'the-bumblezone',
      'ad-astra',
      'blue-skies',
    ],
  },
  {
    id: 'terror',
    label: 'Terror',
    description: 'Horror, criaturas y tensión nocturna',
    slugs: [
      'from-the-fog',
      'cave-dweller-reimagined',
      'the-man-from-the-fog',
      'horror-element-mod',
      'goety',
      'the-graveyard',
      'born-in-chaos',
      'sculk-horde',
      'the-knocker',
    ],
  },
  {
    id: 'magia',
    label: 'Magia',
    description: 'Hechizos, rituales y escuelas arcanas',
    slugs: [
      'ars-nouveau',
      'iron-spells-n-spellbooks',
      'occultism',
      'malum',
      'botania',
      'blood-magic',
      'hexerei',
      'eidolon',
      'relics-mod',
      'apotheosis',
    ],
  },
  {
    id: 'tecnologia',
    label: 'Tecnología',
    description: 'Maquinaria, energía y automatización',
    slugs: [
      'create',
      'flywheel',
      'mekanism',
      'immersive-engineering',
      'thermal-expansion',
      'thermal-foundation',
      'thermal-dynamics',
      'applied-energistics-2',
      'refined-storage',
      'pneumaticcraft-repressurized',
      'industrial-foregoing',
    ],
  },
  {
    id: 'construccion',
    label: 'Construcción',
    description: 'Decoración, muebles y bloques estéticos',
    slugs: [
      'chipped',
      'another-furniture',
      'handcrafted',
      'decorative-blocks',
      'macaws-bridges',
      'macaws-doors',
      'macaws-fences-and-walls',
      'macaws-windows',
      'domum-ornamentum',
      'framedblocks',
      'architects-palette',
      'quark',
    ],
  },
  {
    id: 'naturaleza',
    label: 'Naturaleza y mobs',
    description: 'Fauna, flora y criaturas del overworld',
    slugs: [
      'alexs-mobs',
      'naturalist',
      'friends-and-foes',
      'critters-and-companions',
      'autumnity',
      'environmental',
      'upgrade-aquatic',
      'buzzier-bees',
      'wilderwild',
      'terralith',
    ],
  },
  {
    id: 'comida',
    label: 'Comida y granjas',
    description: 'Cultivos, cocina y economía agrícola',
    slugs: [
      'farmers-delight',
      'brewin-and-chewin',
      'croptopia',
      'cultural-delights',
      'ends-delight',
      'nethers-delight',
      'ocean-delight',
      'miners-delight',
      'delightful',
      'vintagedelight',
    ],
  },
  {
    id: 'almacenamiento',
    label: 'Almacenamiento',
    description: 'Cofres, redes y organización de items',
    slugs: [
      'storage-drawers',
      'sophisticated-backpacks',
      'sophisticated-storage',
      'toms-storage',
      'iron-chests',
      'iron-furnaces',
      'pipez',
      'functional-storage',
      'sophisticated-core',
    ],
  },
  {
    id: 'shaders',
    label: 'Shaders y gráficos',
    description: 'Optimización visual compatible con Forge 1.19',
    slugs: [
      'rubidium',
      'oculus',
      'entity-texture-features',
      'not-enough-animations',
      'fallingleaves-forge',
      'presence-footsteps-forge',
      'farsight',
      'enhanced-celestials',
      'entity-model-features',
      'enhanced-boss-bars',
    ],
  },
  {
    id: 'utilidad',
    label: 'Utilidad',
    description: 'HUD, mapas, atajos e interfaz',
    slugs: [
      'jei',
      'journeymap',
      'controlling',
      'appleskin',
      'mouse-tweaks',
      'inventory-profiles-next',
      'just-enough-resources-jer',
      'ftb-chunks',
      'ftb-teams',
      'light-overlay',
      'jade',
      'trashslot',
    ],
  },
  {
    id: 'rendimiento',
    label: 'Rendimiento',
    description: 'Menos lag, mejor TPS y arranque más rápido',
    slugs: [
      'ferritecore',
      'lazy-dfu-forge',
      'starlight-forge',
      'modernfix',
      'clumps',
      'smooth-boot',
      'memory-settings',
      'fastload',
      'dynamic-fps',
      'smooth-chunk-save',
    ],
  },
  {
    id: 'combate',
    label: 'Combate',
    description: 'Armas, animaciones, bosses y progresión',
    slugs: [
      'better-combat',
      'epic-fight-mod',
      'spartan-weaponry',
      'attributeslib',
      'simply-swords',
      'mowzies-mobs',
      'cataclysm',
      'ice-and-fire-dragons',
      'aquamirae',
      'guard-villagers',
      'mutant-monsters',
    ],
  },
  {
    id: 'calidad-vida',
    label: 'Calidad de vida',
    description: 'Pequeños cambios que mejoran el día a día',
    slugs: [
      'carry-on',
      'comforts',
      'corpse',
      'gravestone-mod',
      'easy-villagers',
      'trading-post',
      'collective',
      'open-parties-and-claims',
      'sit',
      'tree-harvester',
      'vein-mining',
      'stack-refill',
    ],
  },
];
